/**
 * searchDatabase.ts
 * 종목 검색 데이터베이스
 * - 미국 개별주식 (S&P500 + Russell 1000) - 한국어 이름 포함
 * - 한국 개별주식 대표 300
 * - 한국 ETF 순자금 상위 250
 * - 미국 ETF 순자금 상위 300
 */

export type StockCategory = 'us-stock' | 'kr-stock' | 'us-etf' | 'kr-etf';

export interface StockEntry {
  ticker: string;
  name: string;
  nameKr?: string;
  category: StockCategory;
}

// Compact tuple format: [ticker, englishName] or [ticker, englishName, koreanName]
type R = [string, string] | [string, string, string];

const toEntry = (cat: StockCategory) => ([t, n, k]: any): StockEntry => ({
  ticker: t,
  name: n,
  nameKr: k,
  category: cat,
});

// ─────────────────────────────────────────────────────────────
// 미국 개별주식 (S&P500 + 추가 Russell 1000)
// ─────────────────────────────────────────────────────────────
const US_STOCKS_RAW: R[] = [
  ['AAPL','Apple Inc.','애플'],
  ['MSFT','Microsoft Corp.','마이크로소프트'],
  ['NVDA','NVIDIA Corp.','엔비디아'],
  ['AMZN','Amazon.com Inc.','아마존'],
  ['GOOGL','Alphabet Inc. Class A','알파벳(구글)'],
  ['GOOG','Alphabet Inc. Class C','알파벳(구글)'],
  ['META','Meta Platforms Inc.','메타'],
  ['BRK.B','Berkshire Hathaway Class B','버크셔 해서웨이'],
  ['BRK.A','Berkshire Hathaway Class A','버크셔 해서웨이'],
  ['TSLA','Tesla Inc.','테슬라'],
  ['LLY','Eli Lilly and Co.','일라이 릴리'],
  ['AVGO','Broadcom Inc.','브로드컴'],
  ['JPM','JPMorgan Chase & Co.','JP모건 체이스'],
  ['XOM','Exxon Mobil Corp.','엑슨모빌'],
  ['UNH','UnitedHealth Group Inc.','유나이티드헬스'],
  ['V','Visa Inc.','비자'],
  ['MA','Mastercard Inc.','마스터카드'],
  ['COST','Costco Wholesale Corp.','코스트코'],
  ['JNJ','Johnson & Johnson','존슨앤존슨'],
  ['HD','Home Depot Inc.','홈디포'],
  ['PG','Procter & Gamble Co.','P&G'],
  ['ABBV','AbbVie Inc.','애브비'],
  ['NFLX','Netflix Inc.','넷플릭스'],
  ['BAC','Bank of America Corp.','뱅크오브아메리카'],
  ['KO','Coca-Cola Co.','코카콜라'],
  ['WMT','Walmart Inc.','월마트'],
  ['MRK','Merck & Co. Inc.','머크'],
  ['CRM','Salesforce Inc.','세일즈포스'],
  ['AMD','Advanced Micro Devices Inc.','AMD'],
  ['CVX','Chevron Corp.','셰브론'],
  ['ORCL','Oracle Corp.','오라클'],
  ['ADBE','Adobe Inc.','어도비'],
  ['PEP','PepsiCo Inc.','펩시코'],
  ['TMO','Thermo Fisher Scientific Inc.','써모 피셔 사이언티픽'],
  ['ACN','Accenture plc','액센츄어'],
  ['LIN','Linde plc','린데'],
  ['CSCO','Cisco Systems Inc.','시스코'],
  ['ABT','Abbott Laboratories','애보트'],
  ['MCD','McDonald\'s Corp.','맥도날드'],
  ['WFC','Wells Fargo & Co.','웰스 파고'],
  ['IBM','IBM Corp.','IBM'],
  ['DHR','Danaher Corp.','다나허'],
  ['GE','GE Aerospace','GE 에어로스페이스'],
  ['CAT','Caterpillar Inc.','캐터필러'],
  ['INTU','Intuit Inc.','인투이트'],
  ['QCOM','Qualcomm Inc.','퀄컴'],
  ['TXN','Texas Instruments Inc.','텍사스 인스트루먼트'],
  ['NOW','ServiceNow Inc.','서비스나우'],
  ['GS','Goldman Sachs Group Inc.','골드만삭스'],
  ['AMGN','Amgen Inc.','암젠'],
  ['RTX','RTX Corp.','RTX'],
  ['SPGI','S&P Global Inc.','S&P 글로벌'],
  ['VZ','Verizon Communications Inc.','버라이즌'],
  ['ISRG','Intuitive Surgical Inc.','인튜이티브 서지컬'],
  ['T','AT&T Inc.','AT&T'],
  ['PFE','Pfizer Inc.','화이자'],
  ['BKNG','Booking Holdings Inc.','부킹 홀딩스'],
  ['AXP','American Express Co.','아메리칸 익스프레스'],
  ['MS','Morgan Stanley','모건 스탠리'],
  ['AMAT','Applied Materials Inc.','어플라이드 머티리얼즈'],
  ['BLK','BlackRock Inc.','블랙록'],
  ['LOW','Lowe\'s Companies Inc.','로우스'],
  ['SYK','Stryker Corp.','스트라이커'],
  ['HON','Honeywell International Inc.','하니웰'],
  ['LRCX','Lam Research Corp.','램 리서치'],
  ['DE','Deere & Company','디어 앤 컴퍼니'],
  ['PLD','Prologis Inc.','프롤로지스'],
  ['MMC','Marsh & McLennan Companies Inc.','마시 앤 맥레넌'],
  ['C','Citigroup Inc.','씨티그룹'],
  ['PANW','Palo Alto Networks Inc.','팔로알토 네트웍스'],
  ['BSX','Boston Scientific Corp.','보스턴 사이언티픽'],
  ['SCHW','Charles Schwab Corp.','찰스 슈왑'],
  ['ADP','Automatic Data Processing Inc.','ADP'],
  ['MU','Micron Technology Inc.','마이크론 테크놀로지'],
  ['ADI','Analog Devices Inc.','아날로그 디바이시스'],
  ['VRTX','Vertex Pharmaceuticals Inc.','버텍스 파마슈티컬스'],
  ['ETN','Eaton Corp.','이튼'],
  ['UBER','Uber Technologies Inc.','우버'],
  ['CB','Chubb Ltd.','처브'],
  ['GILD','Gilead Sciences Inc.','길리어드 사이언시스'],
  ['REGN','Regeneron Pharmaceuticals Inc.','리제네론'],
  ['UNP','Union Pacific Corp.','유니온 퍼시픽'],
  ['AON','Aon plc','아온'],
  ['KLAC','KLA Corp.','KLA'],
  ['CI','The Cigna Group','시그나'],
  ['CME','CME Group Inc.','CME 그룹'],
  ['INTC','Intel Corp.','인텔'],
  ['BX','Blackstone Inc.','블랙스톤'],
  ['ICE','Intercontinental Exchange Inc.','인터컨티넨털 익스체인지'],
  ['DUK','Duke Energy Corp.','듀크 에너지'],
  ['MDT','Medtronic plc','메드트로닉'],
  ['CDNS','Cadence Design Systems Inc.','케이던스 디자인 시스템'],
  ['SO','Southern Co.','서던 컴퍼니'],
  ['PH','Parker-Hannifin Corp.','파커-하니핀'],
  ['SNPS','Synopsys Inc.','시놉시스'],
  ['TJX','TJX Companies Inc.','TJX'],
  ['ZTS','Zoetis Inc.','조에티스'],
  ['EQIX','Equinix Inc.','에퀴닉스'],
  ['USB','U.S. Bancorp','US 뱅코프'],
  ['MCO','Moody\'s Corp.','무디스'],
  ['SHW','Sherwin-Williams Co.','셔윈-윌리엄스'],
  ['WELL','Welltower Inc.','웰타워'],
  ['NOC','Northrop Grumman Corp.','노스럽 그루먼'],
  ['EMR','Emerson Electric Co.','에머슨 일렉트릭'],
  ['WM','Waste Management Inc.','웨이스트 매니지먼트'],
  ['MSI','Motorola Solutions Inc.','모토로라 솔루션스'],
  ['FCX','Freeport-McMoRan Inc.','프리포트-맥모란'],
  ['MMM','3M Co.','3M'],
  ['APH','Amphenol Corp.','암페놀'],
  ['COP','ConocoPhillips','코노코필립스'],
  ['EOG','EOG Resources Inc.','EOG 리소시스'],
  ['FDX','FedEx Corp.','페덱스'],
  ['NSC','Norfolk Southern Corp.','노퍽 서던'],
  ['ITW','Illinois Tool Works Inc.','일리노이 툴 웍스'],
  ['GD','General Dynamics Corp.','제너럴 다이나믹스'],
  ['LMT','Lockheed Martin Corp.','록히드 마틴'],
  ['PSA','Public Storage','퍼블릭 스토리지'],
  ['HCA','HCA Healthcare Inc.','HCA 헬스케어'],
  ['OKE','ONEOK Inc.','원오케이'],
  ['CTAS','Cintas Corp.','신타스'],
  ['CEG','Constellation Energy Corp.','컨스텔레이션 에너지'],
  ['EW','Edwards Lifesciences Corp.','에드워즈 라이프사이언시스'],
  ['RSG','Republic Services Inc.','리퍼블릭 서비시스'],
  ['APD','Air Products and Chemicals Inc.','에어 프로덕츠'],
  ['TT','Trane Technologies plc','트레인 테크놀로지스'],
  ['CARR','Carrier Global Corp.','캐리어 글로벌'],
  ['PCAR','PACCAR Inc.','팩카'],
  ['AJG','Arthur J. Gallagher & Co.','아서 갤러거'],
  ['FICO','Fair Isaac Corp.','페어 아이작'],
  ['MCHP','Microchip Technology Inc.','마이크로칩 테크놀로지'],
  ['AFL','Aflac Inc.','애플락'],
  ['MPC','Marathon Petroleum Corp.','마라톤 페트롤리엄'],
  ['PSX','Phillips 66','필립스 66'],
  ['AIG','American International Group Inc.','AIG'],
  ['NEM','Newmont Corp.','뉴몬트'],
  ['ECL','Ecolab Inc.','에코랩'],
  ['TDG','TransDigm Group Inc.','트랜스다임'],
  ['HLT','Hilton Worldwide Holdings Inc.','힐튼'],
  ['URI','United Rentals Inc.','유나이티드 렌탈스'],
  ['SRE','Sempra','셈프라'],
  ['VLO','Valero Energy Corp.','발레로 에너지'],
  ['BK','Bank of New York Mellon Corp.','뉴욕 멜론 은행'],
  ['DXCM','DexCom Inc.','덱스콤'],
  ['GWW','W.W. Grainger Inc.','W.W. 그레인저'],
  ['ALL','Allstate Corp.','올스테이트'],
  ['IDXX','IDEXX Laboratories Inc.','아이덱스 레버러토리스'],
  ['KMB','Kimberly-Clark Corp.','킴벌리-클라크'],
  ['D','Dominion Energy Inc.','도미니언 에너지'],
  ['PWR','Quanta Services Inc.','퀀타 서비시스'],
  ['SLB','SLB (Schlumberger)','슐럼베르거'],
  ['FAST','Fastenal Co.','파스테날'],
  ['PAYX','Paychex Inc.','페이첵스'],
  ['ROK','Rockwell Automation Inc.','록웰 오토메이션'],
  ['CMI','Cummins Inc.','커민스'],
  ['PNC','PNC Financial Services Group Inc.','PNC 파이낸셜'],
  ['KMI','Kinder Morgan Inc.','킨더 모건'],
  ['OTIS','Otis Worldwide Corp.','오티스'],
  ['A','Agilent Technologies Inc.','에질런트 테크놀로지스'],
  ['F','Ford Motor Co.','포드'],
  ['GM','General Motors Co.','GM'],
  ['JCI','Johnson Controls International plc','존슨 컨트롤스'],
  ['EXC','Exelon Corp.','엑셀론'],
  ['AME','AMETEK Inc.','에메텍'],
  ['CL','Colgate-Palmolive Co.','콜게이트-파몰리브'],
  ['VRSK','Verisk Analytics Inc.','베리스크 애널리틱스'],
  ['GLW','Corning Inc.','코닝'],
  ['DAL','Delta Air Lines Inc.','델타 항공'],
  ['MNST','Monster Beverage Corp.','몬스터 베버리지'],
  ['EA','Electronic Arts Inc.','일렉트로닉 아츠'],
  ['XEL','Xcel Energy Inc.','엑셀 에너지'],
  ['DOW','Dow Inc.','다우'],
  ['PPG','PPG Industries Inc.','PPG 인더스트리스'],
  ['ODFL','Old Dominion Freight Line Inc.','올드 도미니언 프레이트'],
  ['CPRT','Copart Inc.','코파트'],
  ['GPN','Global Payments Inc.','글로벌 페이먼트스'],
  ['MTD','Mettler-Toledo International Inc.','메틀러-톨레도'],
  ['WAB','Westinghouse Air Brake Technologies Corp.','웨스팅하우스 에어 브레이크'],
  ['KVUE','Kenvue Inc.','켄뷰'],
  ['AXON','Axon Enterprise Inc.','액슨'],
  ['MPWR','Monolithic Power Systems Inc.','모놀리틱 파워 시스템즈'],
  ['WTW','Willis Towers Watson plc','윌리스 타워스 왓슨'],
  ['IQV','IQVIA Holdings Inc.','IQVIA'],
  ['RCL','Royal Caribbean Cruises Ltd.','로열 캐리비안'],
  ['LHX','L3Harris Technologies Inc.','L3해리스 테크놀로지스'],
  ['GEHC','GE HealthCare Technologies Inc.','GE 헬스케어'],
  ['CTVA','Corteva Inc.','코르테바'],
  ['BIIB','Biogen Inc.','바이오젠'],
  ['DVN','Devon Energy Corp.','데번 에너지'],
  ['IR','Ingersoll Rand Inc.','잉거솔 랜드'],
  ['ON','ON Semiconductor Corp.','온 세미컨덕터'],
  ['ELV','Elevance Health Inc.','엘리반스 헬스'],
  ['DECK','Deckers Outdoor Corp.','데커스 아웃도어'],
  ['SBUX','Starbucks Corp.','스타벅스'],
  ['BAX','Baxter International Inc.','백스터'],
  ['NET','Cloudflare Inc.','클라우드플레어'],
  ['SNAP','Snap Inc.','스냅'],
  ['SHOP','Shopify Inc.','쇼피파이'],
  ['SQ','Block Inc.','블록(스퀘어)'],
  ['SPOT','Spotify Technology SA','스포티파이'],
  ['RBLX','Roblox Corp.','로블록스'],
  ['HOOD','Robinhood Markets Inc.','로빈후드'],
  ['COIN','Coinbase Global Inc.','코인베이스'],
  ['LYFT','Lyft Inc.','리프트'],
  ['PINS','Pinterest Inc.','핀터레스트'],
  ['TWLO','Twilio Inc.','트윌리오'],
  ['ZM','Zoom Video Communications Inc.','줌'],
  ['ROKU','Roku Inc.','로쿠'],
  ['DOCU','DocuSign Inc.','도큐사인'],
  ['PLTR','Palantir Technologies Inc.','팔란티어'],
  ['RIVN','Rivian Automotive Inc.','리비안'],
  ['LCID','Lucid Group Inc.','루시드'],
  ['NIO','NIO Inc.','니오'],
  ['BABA','Alibaba Group Holding Ltd.','알리바바'],
  ['JD','JD.com Inc.','징둥닷컴'],
  ['PDD','PDD Holdings Inc.','핀둬둬'],
  ['BIDU','Baidu Inc.','바이두'],
  ['TCEHY','Tencent Holdings Ltd.','텐센트'],
  ['TSM','Taiwan Semiconductor Manufacturing Co.','TSMC'],
  ['ASML','ASML Holding NV','ASML'],
  ['SAP','SAP SE','SAP'],
  ['TM','Toyota Motor Corp.','도요타'],
  ['NVS','Novartis AG','노바티스'],
  ['AZN','AstraZeneca plc','아스트라제네카'],
  ['SHEL','Shell plc','셸'],
  ['UL','Unilever plc','유니레버'],
  ['ARM','Arm Holdings plc','ARM 홀딩스'],
  ['SMCI','Super Micro Computer Inc.','수퍼 마이크로 컴퓨터'],
  ['APP','Applovin Corp.','앱러빈'],
  ['CRWD','CrowdStrike Holdings Inc.','크라우드스트라이크'],
  ['SNOW','Snowflake Inc.','스노우플레이크'],
  ['MDB','MongoDB Inc.','몽고DB'],
  ['DDOG','Datadog Inc.','데이터독'],
  ['ZS','Zscaler Inc.','지스케일러'],
  ['FTNT','Fortinet Inc.','포티넷'],
  ['OKTA','Okta Inc.','옥타'],
  ['HubS','HubSpot Inc.','허브스팟'],
  ['HUBS','HubSpot Inc.','허브스팟'],
  ['TTD','The Trade Desk Inc.','더 트레이드 데스크'],
  ['ABNB','Airbnb Inc.','에어비앤비'],
  ['DASH','DoorDash Inc.','도어대시'],
  ['U','Unity Software Inc.','유니티'],
  ['PATH','UiPath Inc.','유아이패스'],
  ['AI','C3.ai Inc.','C3.ai'],
  ['GTLB','GitLab Inc.','깃랩'],
  ['IOT','Samsara Inc.','삼사라'],
  ['BILL','Bill Holdings Inc.','빌 홀딩스'],
  ['CELH','Celsius Holdings Inc.','셀시우스'],
  ['MSTR','MicroStrategy Inc.','마이크로스트래티지'],
  ['GME','GameStop Corp.','게임스탑'],
  ['AMC','AMC Entertainment Holdings Inc.','AMC 엔터테인먼트'],
  ['CVNA','Carvana Co.','카바나'],
  ['SOFI','SoFi Technologies Inc.','소파이'],
  ['AFRM','Affirm Holdings Inc.','어펌'],
  ['UPST','Upstart Holdings Inc.','업스타트'],
  ['LC','LendingClub Corp.','렌딩클럽'],
  ['OPEN','Opendoor Technologies Inc.','오픈도어'],
  ['CLOV','Clover Health Investments Corp.','클로버 헬스'],
  ['WKHS','Workhorse Group Inc.','워크호스'],
  ['NKLA','Nikola Corp.','니콜라'],
  ['SPCE','Virgin Galactic Holdings Inc.','버진 갤럭틱'],
  ['WISH','ContextLogic Inc.','위시'],
  ['LUMN','Lumen Technologies Inc.','루멘 테크놀로지스'],
  ['PARA','Paramount Global','파라마운트'],
  ['WBD','Warner Bros. Discovery Inc.','워너 브라더스 디스커버리'],
  ['DIS','The Walt Disney Co.','월트 디즈니'],
  ['CMCSA','Comcast Corp.','컴캐스트'],
  ['CHTR','Charter Communications Inc.','차터 커뮤니케이션즈'],
  ['NWSA','News Corp Class A','뉴스코프'],
  ['FOX','Fox Corp. Class B','폭스'],
  ['FOXA','Fox Corp. Class A','폭스'],
  ['NYT','New York Times Co.','뉴욕 타임스'],
  ['SIRI','Sirius XM Holdings Inc.','시리우스 XM'],
  ['IPG','Interpublic Group of Companies Inc.','인터퍼블릭 그룹'],
  ['OMC','Omnicom Group Inc.','옴니콤'],
  ['WPP','WPP plc','WPP'],
  ['TTWO','Take-Two Interactive Software Inc.','테이크투 인터랙티브'],
  ['ATVI','Activision Blizzard Inc.','액티비전 블리자드'],
  ['NTES','NetEase Inc.','넷이즈'],
  ['SE','Sea Ltd.','씨 리미티드'],
  ['GRAB','Grab Holdings Ltd.','그랩'],
  ['GOTO','GoTo Group','고투 그룹'],
  ['MELI','MercadoLibre Inc.','메르카도리브레'],
  ['NU','Nu Holdings Ltd.','누 홀딩스'],
  ['StoneCo','StoneCo Ltd.','스톤코'],
  ['STNE','StoneCo Ltd.','스톤코'],
  ['PAGS','PagSeguro Digital Ltd.','팍시구로'],
  ['XP','XP Inc.','XP Inc.'],
  ['VALE','Vale S.A.','발레'],
  ['PBR','Petróleo Brasileiro S.A.','페트로브라스'],
  ['ITUB','Itaú Unibanco Holding SA','이타우 우니방코'],
  ['BBD','Banco Bradesco SA','반코 브라데스코'],
  ['ABV','Ambev SA','암베브'],
  ['SID','Companhia Siderúrgica Nacional','CSN'],
  ['GFI','Gold Fields Ltd.','골드 필즈'],
  ['HMY','Harmony Gold Mining Co. Ltd.','하모니 골드'],
  ['HL','Hecla Mining Co.','헤클라 마이닝'],
  ['AG','First Majestic Silver Corp.','퍼스트 마제스틱 실버'],
  ['CDE','Coeur Mining Inc.','쾨르 마이닝'],
  ['WPM','Wheaton Precious Metals Corp.','휘튼 프레셔스 메탈즈'],
  ['KGC','Kinross Gold Corp.','키노스 골드'],
  ['AEM','Agnico Eagle Mines Ltd.','아그니코 이글'],
  ['GOLD','Barrick Gold Corp.','배릭 골드'],
  ['NUE','Nucor Corp.','뉴코'],
  ['STLD','Steel Dynamics Inc.','스틸 다이나믹스'],
  ['X','United States Steel Corp.','US 스틸'],
  ['CLF','Cleveland-Cliffs Inc.','클리블랜드-클리프스'],
  ['AA','Alcoa Corp.','알코아'],
  ['RIO','Rio Tinto plc','리오 틴토'],
  ['BHP','BHP Group Ltd.','BHP'],
  ['TECK','Teck Resources Ltd.','텍 리소시스'],
  ['LYB','LyondellBasell Industries NV','라이온델바셀'],
  ['CE','Celanese Corp.','셀라니즈'],
  ['DD','DuPont de Nemours Inc.','듀폰'],
  ['ALB','Albemarle Corp.','알베말레'],
  ['MP','MP Materials Corp.','MP 머티리얼즈'],
  ['LTHM','Livent Corp.','라이벤트'],
  ['SQM','Sociedad Quimica y Minera de Chile SA','SQM'],
  ['MOS','Mosaic Co.','모자이크'],
  ['CF','CF Industries Holdings Inc.','CF 인더스트리스'],
  ['FMC','FMC Corp.','FMC'],
  ['ICL','ICL Group Ltd.','ICL 그룹'],
  ['GNRC','Generac Holdings Inc.','제네락'],
  ['PHM','PulteGroup Inc.','풀테그룹'],
  ['LEN','Lennar Corp.','레나'],
  ['TOL','Toll Brothers Inc.','톨 브라더스'],
  ['DHI','D.R. Horton Inc.','D.R. 호턴'],
  ['NVR','NVR Inc.','NVR'],
  ['MDC','MDC Holdings Inc.','MDC 홀딩스'],
  ['BZH','Beazer Homes USA Inc.','비저 홈스'],
  ['KBH','KB Home','KB 홈'],
  ['MHO','M/I Homes Inc.','M/I 홈스'],
  ['SKY','Skyline Champion Corp.','스카이라인 챔피언'],
  ['CVS','CVS Health Corp.','CVS 헬스'],
  ['WBA','Walgreens Boots Alliance Inc.','월그린스 부츠 얼라이언스'],
  ['RAD','Rite Aid Corp.','라이트 에이드'],
  ['ACI','Albertsons Companies Inc.','앨버슨스'],
  ['KR','Kroger Co.','크로거'],
  ['SFM','Sprouts Farmers Market Inc.','스프라우츠 파머스 마켓'],
  ['GO','Grocery Outlet Holding Corp.','그로서리 아웃렛'],
  ['ARCO','Arcos Dorados Holdings Inc.','아르코스 도라도스'],
  ['QSR','Restaurant Brands International Inc.','레스토랑 브랜즈'],
  ['YUM','Yum! Brands Inc.','얌! 브랜즈'],
  ['DPZ','Domino\'s Pizza Inc.','도미노 피자'],
  ['WING','Wingstop Inc.','윙스탑'],
  ['TXRH','Texas Roadhouse Inc.','텍사스 로드하우스'],
  ['SHAK','Shake Shack Inc.','쉐이크쉑'],
  ['CMG','Chipotle Mexican Grill Inc.','치폴레'],
  ['EAT','Brinker International Inc.','브링커 인터내셔널'],
  ['DRI','Darden Restaurants Inc.','다든 레스토랑'],
  ['BJRI','BJ\'s Restaurants Inc.','BJ\'s 레스토랑'],
  ['JACK','Jack in the Box Inc.','잭 인 더 박스'],
  ['NCLH','Norwegian Cruise Line Holdings Ltd.','노르웨지안 크루즈'],
  ['CCL','Carnival Corp.','카니발'],
  ['MAR','Marriott International Inc.','매리어트'],
  ['H','Hyatt Hotels Corp.','하얏트 호텔'],
  ['CHH','Choice Hotels International Inc.','초이스 호텔'],
  ['WH','Wyndham Hotels & Resorts Inc.','윈덤 호텔'],
  ['HGV','Hilton Grand Vacations Inc.','힐튼 그랜드 베케이션스'],
  ['SIX','Six Flags Entertainment Corp.','식스 플래그스'],
  ['FUN','Cedar Fair LP','시더 페어'],
  ['SEAS','SeaWorld Entertainment Inc.','씨월드 엔터테인먼트'],
  ['LVS','Las Vegas Sands Corp.','라스베이거스 샌즈'],
  ['WYNN','Wynn Resorts Ltd.','윈 리조트'],
  ['MGM','MGM Resorts International','MGM 리조트'],
  ['CZR','Caesars Entertainment Inc.','시저스 엔터테인먼트'],
  ['DKNG','DraftKings Inc.','드래프트킹스'],
  ['RSI','Rush Street Interactive Inc.','러시 스트리트 인터랙티브'],
  ['GAN','GAN Ltd.','GAN'],
  ['EVRI','Everi Holdings Inc.','에버리'],
  ['NLY','Annaly Capital Management Inc.','아날리 캐피털'],
  ['AGNC','AGNC Investment Corp.','AGNC 인베스트먼트'],
  ['MFA','MFA Financial Inc.','MFA 파이낸셜'],
  ['TWO','Two Harbors Investment Corp.','투 하버스'],
  ['IVR','Invesco Mortgage Capital Inc.','인베스코 모기지 캐피털'],
  ['WU','Western Union Co.','웨스턴 유니온'],
  ['FIS','Fidelity National Information Services Inc.','피델리티 내셔널 정보서비스'],
  ['FISV','Fiserv Inc.','파이저브'],
  ['AMP','Ameriprise Financial Inc.','아메리프라이즈 파이낸셜'],
  ['PRU','Prudential Financial Inc.','프루덴셜 파이낸셜'],
  ['MET','MetLife Inc.','메트라이프'],
  ['UNM','Unum Group','유넘 그룹'],
  ['LNC','Lincoln National Corp.','링컨 내셔널'],
  ['GL','Globe Life Inc.','글로브 라이프'],
  ['PFG','Principal Financial Group Inc.','프린시펄 파이낸셜'],
  ['EG','Everest Group Ltd.','에버레스트 그룹'],
  ['RE','Everest Re Group Ltd.','에버레스트 리'],
  ['RNR','RenaissanceRe Holdings Ltd.','르네상스리'],
  ['MKL','Markel Group Inc.','마켈'],
  ['RLI','RLI Corp.','RLI'],
  ['HIG','Hartford Financial Services Group Inc.','하트포드 파이낸셜'],
  ['TRV','Travelers Companies Inc.','트래블러스'],
  ['PGR','Progressive Corp.','프로그레시브'],
  ['AFG','American Financial Group Inc.','아메리칸 파이낸셜'],
  ['WRB','W.R. Berkley Corp.','W.R. 버클리'],
  ['CINF','Cincinnati Financial Corp.','신시내티 파이낸셜'],
  ['SFG','StanCorp Financial Group Inc.','스탠코프 파이낸셜'],
  ['NTRS','Northern Trust Corp.','노던 트러스트'],
  ['STT','State Street Corp.','스테이트 스트리트'],
  ['TROW','T. Rowe Price Group Inc.','T. 로우 프라이스'],
  ['IVZ','Invesco Ltd.','인베스코'],
  ['WDR','Waddell & Reed Financial Inc.','와델 앤 리드'],
  ['AMG','Affiliated Managers Group Inc.','어필리에이티드 매니저스'],
  ['APAM','Artisan Partners Asset Management Inc.','아르티산 파트너스'],
  ['HLNE','Hamilton Lane Inc.','해밀턴 레인'],
  ['KKR','KKR & Co. Inc.','KKR'],
  ['CG','Carlyle Group Inc.','칼라일 그룹'],
  ['APO','Apollo Global Management Inc.','아폴로 글로벌 매니지먼트'],
  ['BAM','Brookfield Asset Management Ltd.','브룩필드 자산운용'],
  ['ARES','Ares Management Corp.','에어리스 매니지먼트'],
  ['OWL','Blue Owl Capital Inc.','블루 아울 캐피털'],
  ['TPG','TPG Inc.','TPG'],
  ['HTGC','Hercules Capital Inc.','헤라클레스 캐피털'],
  ['ARCC','Ares Capital Corp.','에어리스 캐피털'],
  ['FSK','FS KKR Capital Corp.','FS KKR 캐피털'],
  ['MAIN','Main Street Capital Corp.','메인 스트리트 캐피털'],
  ['OBDC','Blue Owl Capital Corp.','블루 아울 캐피털'],
  ['GBDC','Golub Capital BDC Inc.','골럽 캐피털 BDC'],
  ['TPVG','TriplePoint Venture Growth BDC Corp.','트리플포인트 벤처'],
  ['ORCC','Owl Rock Capital Corp.','아울 록 캐피털'],
  ['NEWT','NewtekOne Inc.','뉴텍원'],
  ['BCSF','Bain Capital Specialty Finance Inc.','베인 캐피털 스페셜티'],
  ['WHR','Whirlpool Corp.','월풀'],
  ['NWL','Newell Brands Inc.','뉴웰 브랜즈'],
  ['FBHS','Fortune Brands Innovations Inc.','포춘 브랜즈'],
  ['MHK','Mohawk Industries Inc.','모호크 인더스트리스'],
  ['TPX','Tempur Sealy International Inc.','템퍼 실리'],
  ['PRGO','Perrigo Company plc','페리고'],
  ['ZBH','Zimmer Biomet Holdings Inc.','짐머 바이오멧'],
  ['HAE','Haemonetics Corp.','해모네틱스'],
  ['TFX','Teleflex Inc.','텔레플렉스'],
  ['HOLX','Hologic Inc.','홀로직'],
  ['PODD','Insulet Corp.','인술렛'],
  ['NVCR','NovoCure Ltd.','노보큐어'],
  ['BFLY','Butterfly Network Inc.','버터플라이 네트워크'],
  ['INSP','Inspire Medical Systems Inc.','인스파이어 메디컬'],
  ['SWAV','ShockWave Medical Inc.','쇼크웨이브 메디컬'],
  ['IRTC','iRhythm Technologies Inc.','아이리듬 테크놀로지스'],
  ['PHR','Phreesia Inc.','프리지아'],
  ['OMCL','Omnicell Inc.','옴니셀'],
  ['VEEV','Veeva Systems Inc.','비바 시스템즈'],
  ['RMD','ResMed Inc.','레스메드'],
  ['ALGN','Align Technology Inc.','알라인 테크놀로지'],
  ['NVST','Envista Holdings Corp.','엔비스타'],
  ['XRAY','Dentsply Sirona Inc.','덴츠플라이 시로나'],
  ['DVA','DaVita Inc.','다비타'],
  ['FHN','First Horizon Corp.','퍼스트 호라이즌'],
  ['ZION','Zions Bancorporation NA','자이온스'],
  ['FITB','Fifth Third Bancorp','피프스 서드 뱅코프'],
  ['RF','Regions Financial Corp.','리전스 파이낸셜'],
  ['KEY','KeyCorp','키코프'],
  ['HBAN','Huntington Bancshares Inc.','헌팅턴 뱅크셰어스'],
  ['CFG','Citizens Financial Group Inc.','시티즌스 파이낸셜'],
  ['MTB','M&T Bank Corp.','M&T 뱅크'],
  ['CMA','Comerica Inc.','코메리카'],
  ['BOKF','BOK Financial Corp.','BOK 파이낸셜'],
  ['SNV','Synovus Financial Corp.','시노버스'],
  ['UMBF','UMB Financial Corp.','UMB 파이낸셜'],
  ['FFIN','First Financial Bankshares Inc.','퍼스트 파이낸셜 뱅크셰어스'],
  ['IBTX','Independent Bank Group Inc.','인디펜던트 뱅크 그룹'],
  ['TFSL','TFS Financial Corp.','TFS 파이낸셜'],
  ['COLB','Columbia Banking System Inc.','콜럼비아 뱅킹'],
  ['BMRC','Bank of Marin Bancorp','뱅크 오브 마린'],
  // 한국 투자자 인기 종목 추가
  ['IONQ','IonQ Inc.','아이온큐'],
  ['SNDK','SanDisk Corp.','샌디스크'],
  ['IREN','Iris Energy Ltd.','아이리스 에너지'],
  ['RKLB','Rocket Lab USA Inc.','로켓랩'],
  ['JOBY','Joby Aviation Inc.','조비 에비에이션'],
  ['SMR','NuScale Power Corp.','누스케일 파워'],
  ['LITE','Lumentum Holdings Inc.','루멘텀 홀딩스'],
  ['BMNR','BitMine Immersion Technologies Inc.','비트마인 이머전 테크놀로지스'],
  ['CRCL','Circle Internet Group Inc.','써클 인터넷'],
];

// ─────────────────────────────────────────────────────────────
// 한국 개별주식 대표 300
// ─────────────────────────────────────────────────────────────
const KR_STOCKS_RAW: R[] = [
  ['005930.KS','Samsung Electronics','삼성전자'],
  ['000660.KS','SK Hynix','SK하이닉스'],
  ['207940.KS','Samsung Biologics','삼성바이오로직스'],
  ['005380.KS','Hyundai Motor','현대차'],
  ['000270.KS','Kia Corp.','기아'],
  ['051910.KS','LG Chem','LG화학'],
  ['006400.KS','Samsung SDI','삼성SDI'],
  ['035420.KS','NAVER Corp.','네이버'],
  ['005935.KS','Samsung Electronics Preferred','삼성전자 우'],
  ['035720.KS','Kakao Corp.','카카오'],
  ['068270.KS','Celltrion','셀트리온'],
  ['105560.KS','KB Financial Group','KB금융'],
  ['055550.KS','Shinhan Financial Group','신한지주'],
  ['028260.KS','Samsung C&T','삼성물산'],
  ['096770.KS','SK Innovation','SK이노베이션'],
  ['003550.KS','LG Corp.','LG'],
  ['032830.KS','Samsung Life Insurance','삼성생명'],
  ['017670.KS','SK Telecom','SK텔레콤'],
  ['003490.KS','Korean Air','대한항공'],
  ['015760.KS','Korea Electric Power','한국전력'],
  ['010950.KS','S-Oil','S-Oil'],
  ['034730.KS','SK Square','SK스퀘어'],
  ['012330.KS','Hyundai Mobis','현대모비스'],
  ['066570.KS','LG Electronics','LG전자'],
  ['316140.KS','Woori Financial Group','우리금융지주'],
  ['086790.KS','Hana Financial Group','하나금융지주'],
  ['009150.KS','Samsung Electro-Mechanics','삼성전기'],
  ['032640.KS','LG Uplus','LGU+'],
  ['011200.KS','HMM','HMM'],
  ['090430.KS','Amorepacific','아모레퍼시픽'],
  ['000100.KS','Yuhan','유한양행'],
  ['036570.KS','NCsoft','엔씨소프트'],
  ['047050.KS','Daewoo Shipbuilding','대우조선해양'],
  ['042660.KS','Hanwha Ocean','한화오션'],
  ['009540.KS','HD Korea Shipbuilding','HD한국조선해양'],
  ['329180.KS','HD Hyundai Heavy Industries','HD현대중공업'],
  ['011790.KS','SKC','SKC'],
  ['010130.KS','Korea Zinc','고려아연'],
  ['003620.KS','KCC Corp.','KCC'],
  ['006800.KS','Mirae Asset Securities','미래에셋증권'],
  ['000810.KS','Samsung Fire & Marine Insurance','삼성화재'],
  ['034020.KS','Doosan Enerbility','두산에너빌리티'],
  ['267250.KS','HD Hyundai','HD현대'],
  ['088350.KS','Hanwha Life Insurance','한화생명'],
  ['030200.KS','KT Corp.','KT'],
  ['033780.KS','KT&G','KT&G'],
  ['000720.KS','Hyundai Engineering & Construction','현대건설'],
  ['001450.KS','Hyundai Marine & Fire Insurance','현대해상'],
  ['024110.KS','Industrial Bank of Korea','기업은행'],
  ['051600.KS','Jeju Air','제주항공'],
  ['271560.KS','Orion Corp.','오리온'],
  ['402340.KS','SK Square','SK스퀘어2'],
  ['259960.KS','Krafton','크래프톤'],
  ['112040.KS','Wemade','위메이드'],
  ['036460.KS','Korea Gas Corp.','한국가스공사'],
  ['005490.KS','POSCO Holdings','포스코홀딩스'],
  ['002790.KS','POSCO International','포스코인터내셔널'],
  ['003230.KS','Samsung Card','삼성카드'],
  ['009830.KS','Hanwha Solutions','한화솔루션'],
  ['161390.KS','Hankook Tire','한국타이어'],
  ['000120.KS','CJ Corp.','CJ'],
  ['079160.KS','CJ CGV','CJ CGV'],
  ['097950.KS','CJ CheilJedang','CJ제일제당'],
  ['001740.KS','SK Networks','SK네트웍스'],
  ['009420.KS','Hanmi Pharmaceutical','한미약품'],
  ['128940.KS','Hanmi Pharmaceutical Holding','한미사이언스'],
  ['078930.KS','GS Holdings','GS'],
  ['023530.KS','Lotte Shopping','롯데쇼핑'],
  ['004990.KS','Lotte Corp.','롯데지주'],
  ['011170.KS','Lotte Chemical','롯데케미칼'],
  ['050096.KS','Lotte Fine Chemical','롯데정밀화학'],
  ['071050.KS','Korea Investment Holdings','한국금융지주'],
  ['030000.KS','Cheil Worldwide','제일기획'],
  ['000670.KS','YoungOne Corp.','영원무역홀딩스'],
  ['004140.KS','Dongyang Mechatronics','동양물산기업'],
  ['018260.KS','Samsung Publishing','삼성출판사'],
  ['002380.KS','KCC Glass','KCC글라스'],
  ['006360.KS','GS Engineering & Construction','GS건설'],
  ['000480.KS','Chosun Refractories','조선내화'],
  ['006090.KS','Woongjin Coway','코웨이'],
  ['021240.KS','Coway','코웨이2'],
  ['009240.KS','Hanssem','한샘'],
  ['004170.KS','Shinsegae','신세계'],
  ['139480.KS','E-Mart','이마트'],
  ['069960.KS','Hyundai Department Store','현대백화점'],
  ['023590.KS','BGF Retail','BGF리테일'],
  ['282330.KS','BGF Logistics','BGF로지스틱스'],
  ['004370.KS','Nongshim','농심'],
  ['007070.KS','GS Retail','GS리테일'],
  ['012450.KS','Samsung Techwin','한화에어로스페이스'],
  ['047810.KS','Korea Aerospace Industries','한국항공우주'],
  ['064350.KS','Hyundai Rotem','현대로템'],
  ['006260.KS','LS Corp.','LS'],
  ['010120.KS','LS Electric','LS ELECTRIC'],
  ['229640.KS','LS Materials','LS머트리얼즈'],
  ['041830.KS','Korea Shipbuilding & Offshore Eng','이노인스페이스'],
  ['010060.KS','OCI Holdings','OCI홀딩스'],
  ['003010.KS','Bookook Securities','부국증권'],
  ['017940.KS','E1 Corp.','E1'],
  ['081660.KS','Hite Jinro','하이트진로'],
  ['000080.KS','Hite Jinro Holdings','하이트진로홀딩스'],
  ['005300.KS','Lotte Chilsung Beverage','롯데칠성'],
  ['280360.KS','Lotte Wellfood','롯데웰푸드'],
  ['145990.KS','Samlip General Foods','삼립식품'],
  ['007310.KS','Ottogi Corp.','오뚜기'],
  ['002030.KS','Asiana Airlines','아시아나항공'],
  ['020560.KS','Asiana IDT','아시아나IDT'],
  ['001390.KS','Korea High Technology','한미반도체'],
  ['042700.KS','Hanmi Semiconductor','한미반도체2'],
  ['058470.KS','Elentec','엘엔에프'],
  ['066970.KS','L&F','L&F'],
  ['247540.KS','Ecopro BM','에코프로비엠'],
  ['086520.KS','Ecopro Co.','에코프로'],
  ['000240.KS','Hankook Tire Holdings','한국타이어앤테크놀로지'],
  ['014970.KS','Doosan Bobcat','두산밥캣'],
  ['241560.KS','Doosan Fuel Cell','두산퓨얼셀'],
  ['016360.KS','Samsung Securities','삼성증권'],
  ['078000.KS','Daewoong Pharmaceutical','대웅제약'],
  ['069620.KS','Daewoong Biosys','대웅바이오'],
  ['003000.KS','Boryung Pharmaceutical','보령제약'],
  ['000640.KS','Dong-A Socio Holdings','동아쏘시오홀딩스'],
  ['000520.KS','Samchundang Pharmaceutical','삼천당제약'],
  ['185750.KS','Zion Corporation','종근당'],
  ['185750.KS','Jong Geun Dang','종근당'],
  ['000250.KS','Samyang Corp.','삼양홀딩스'],
  ['000070.KS','Samyang Holdings','삼양홀딩스2'],
  ['095570.KS','AJ Networks','AJ네트웍스'],
  ['030210.KS','KlabLock','클랩락'],
  ['010140.KS','Samsung Heavy Industries','삼성중공업'],
  ['009350.KS','Kortek Corp.','한화정밀기계'],
  ['001680.KS','Daesang Corp.','대상'],
  ['003960.KS','Saejin Electronic','사조대림'],
  ['006110.KS','Taekwang Industrial','태광산업'],
  ['001720.KS','Shinhan Financial Holdings','신한금융지주2'],
  ['000060.KS','Meritz Financial Group','메리츠금융지주'],
  ['138040.KS','Meritz Fire and Marine Insurance','메리츠화재'],
  ['009160.KS','Simpac Inc.','심팩'],
  ['011300.KS','Seokyung Co.','성우하이텍'],
  ['047400.KS','Empas Corp.','이엠텍'],
  ['263750.KS','펄어비스','펄어비스'],
  ['036530.KS','SNE Research','에스엔이리서치'],
  ['204210.KS','Moduslink','모두투어'],
  ['900110.KS','OSSTEM Implant','오스템임플란트'],
  ['084370.KS','OSSTEM Implant','오스템임플란트2'],
  ['000990.KS','DB HiTek','DB하이텍'],
  ['005940.KS','NH Investment Securities','NH투자증권'],
  ['016610.KS','DB Insurance','DB손해보험'],
  ['000430.KS','Daehan Flour Mills','대한제분'],
  ['001680.KS','Daesang Corp.','대상2'],
  ['003620.KS','KCC Corp2.','KCC2'],
  ['010620.KS','Hyundai Mipo Dockyard','현대미포조선'],
  ['001530.KS','DI Corp.','동양'],
  ['049770.KS','Dong-A ST','동아에스티'],
  ['001060.KS','JW Pharmaceutical','JW중외제약'],
  ['002350.KS','Nexen Tire','넥센타이어'],
  ['004490.KS','Sebang Global Battery','세방전지'],
  ['002040.KS','S&T Holdings','S&T홀딩스'],
  ['060980.KS','Maeil Holdings','매일홀딩스'],
  ['005250.KS','Green Cross Corp.','녹십자홀딩스'],
  ['006480.KS','Ssangyong Cement Industrial','쌍용C&E'],
  ['003410.KS','Ssangyong C&E','쌍용C&E2'],
  ['001530.KS','Hyundai Elevator','현대엘리베이터'],
  ['017800.KS','Hyundai Elevator2','현대엘리베이터2'],
  ['005180.KS','Binggrae','빙그레'],
  ['000905.KS','LG Corp. Preferred','LG우'],
  ['007310.KS','Ottogi2','오뚜기2'],
  ['002240.KS','Korea Kolmar Holdings','한국콜마홀딩스'],
  ['024720.KS','Korea Kolmar','한국콜마'],
  ['009110.KS','Hyundai Wia','현대위아'],
  ['000640.KS','Dong-A Socio','동아에스티2'],
  ['018880.KS','Handsome Corp.','한섬'],
  ['115390.KS','Reyon Pharmaceutical','레이온제약'],
  ['026940.KS','Bokwang FNB','복광FNB'],
  ['020400.KS','Hana Tour','하나투어'],
  ['032280.KS','Songwon Industrial','송원산업'],
  ['004800.KS','Hyosung Corp.','효성'],
  ['298040.KS','Hyosung TNC','효성TNC'],
  ['004490.KS','Sebang','세방'],
  ['023450.KS','DongKuk Steel','동국제강'],
  ['001230.KS','Dongkuk Holdings','동국홀딩스'],
  ['004020.KS','Hyundai Steel','현대제철'],
  ['010780.KS','ISC Corp.','ISC'],
  ['053270.KS','YG Entertainment','YG엔터테인먼트'],
  ['041510.KS','SM Entertainment','SM엔터테인먼트'],
  ['035900.KS','JYP Entertainment','JYP엔터테인먼트'],
  ['352820.KS','HYBE','하이브'],
  ['035760.KS','CJ ENM','CJ ENM'],
  ['034020.KS','Doosan Enerbility2','두산에너빌리티2'],
  ['018250.KS','Aekyung Industrial','애경산업'],
  ['018880.KS','Handsome2','한섬2'],
  ['004170.KS','Shinsegae2','신세계2'],
  ['016300.KS','Lgnsons','LG생활건강'],
  ['051900.KS','LG H&H','LG생활건강2'],
  ['000400.KS','Lotte Non-Life Insurance','롯데손해보험'],
  ['005965.KS','SK Chemicals Preferred','SKC우'],
  ['029780.KS','Samsung Card2','삼성카드2'],
  ['002600.KS','Poongsan Corp.','풍산'],
  ['005870.KS','Poongsan Holdings','풍산홀딩스'],
  ['050210.KS','Vodia Networks','미래에셋생명'],
  ['085620.KS','Mirae Asset Life Insurance','미래에셋생명2'],
  ['008770.KS','Hotel Shilla','호텔신라'],
  ['280090.KS','Windmill','에쓰씨엔지니어링'],
  ['001680.KS','Daesang3','대상3'],
  ['036800.KS','Ncsoft2','엔씨소프트2'],
  ['454910.KS','Kakao Games','카카오게임즈'],
  ['293490.KS','Kakao Pay','카카오페이'],
  ['035420.KS','Naver2','네이버2'],
  ['376300.KS','Kakao Bank','카카오뱅크'],
  ['003145.KS','Cuckoo Holdings','쿠쿠홀딩스'],
  ['192400.KS','Cuckoo Homesys','쿠쿠홈시스'],
  ['069260.KS','Daewoong Biosys2','대웅바이오2'],
  ['214150.KS','Clasico','클래시코'],
  ['003380.KS','Harim Holdings','하림지주'],
  ['136480.KS','Harim Corp.','하림'],
  ['033250.KS','Chunbo Chemical','천보화학'],
  ['051915.KS','LG Chem Preferred','LG화학 우'],
  ['294870.KS','HDC Hyundai Development','HDC현대개발'],
  ['294820.KS','E&C Property Dvlpmnt','이앤씨개발'],
  ['163560.KS','Medytox','메디톡스'],
  ['196170.KS','Alteogen','알테오젠'],
  ['007570.KS','Ilyang Pharmaceutical','일양약품'],
  ['001430.KS','Sebang Global','세방글로벌'],
  ['007160.KS','Sajo Industries','사조인더스트리'],
  ['001680.KS','Daesang4','대상4'],
  ['000067.KS','Hyundai Motor Preferred 2B','현대차2우B'],
  ['005387.KS','Hyundai Motor Preferred','현대차우'],
  ['000270.KS','Kia Corp2.','기아2'],
  ['267270.KS','HD Hyundai Construction Equipment','HD현대건설기계'],
  ['042670.KS','HD Hyundai Infracore','HD현대인프라코어'],
  ['003450.KS','Hyundai Fire and Marine Insurance','현대해상화재보험'],
  ['032350.KS','Lotte Rental','롯데렌탈'],
  ['011780.KS','Kumho Petrochemical','금호석유'],
  ['051910.KS','LG Chem2','LG화학2'],
  ['458730.KS','LS Eco Energy','LS에코에너지'],
  ['334890.KS','LS Materials','LS머트리얼즈2'],
  ['006650.KS','Kumho Electric','금호전기'],
  ['009900.KS','Kyobo Securities','교보증권'],
  ['030610.KS','KB Securities','교보증권2'],
  ['001720.KS','Shinhan Financial Group2','신한지주2'],
  ['033920.KS','Mucin Co.','무신사'],
  ['256840.KS','Hyundai AutoEver','현대오토에버'],
  ['034950.KS','Korea Investment & Securities','한국투자증권'],
  ['039490.KS','KMI Korean Medical Institute','키움증권'],
  ['097950.KS','CJ CheilJedang2','CJ제일제당2'],
  ['011780.KS','Kumho Petro2','금호석유2'],
  ['453580.KS','Classys','클래시스'],
  ['000545.KS','Hyundai Motor Preferred3','현대차3우B'],
  ['373220.KS','LG Energy Solution','LG에너지솔루션'],
  ['402340.KS','SK Square2','SK스퀘어2'],
  ['000880.KS','Hanwha Corp.','한화'],
  ['272210.KS','Hanwha Systems','한화시스템'],
  ['009290.KS','Kwangdong Pharmaceutical','광동제약'],
];

// ─────────────────────────────────────────────────────────────
// 한국 ETF 순자금 상위
// ─────────────────────────────────────────────────────────────
const KR_ETFS_RAW: R[] = [
  ['069500.KS','KODEX 200','KODEX 200'],
  ['102110.KS','TIGER 200','TIGER 200'],
  ['229200.KS','KODEX 코스닥150','KODEX 코스닥150'],
  ['278540.KS','KODEX MSCI Korea TR','KODEX MSCI Korea TR'],
  ['091160.KS','KODEX 반도체','KODEX 반도체'],
  ['091170.KS','KODEX 은행','KODEX 은행'],
  ['266370.KS','KODEX 코스닥150 레버리지','KODEX 코스닥150 레버리지'],
  ['233740.KS','KODEX 코스닥150 인버스','KODEX 코스닥150 인버스'],
  ['252670.KS','KODEX 200선물인버스2X','KODEX 200선물인버스2X'],
  ['069660.KS','KOSEF 200','KOSEF 200'],
  ['148020.KS','KOSEF 국고채10년','KOSEF 국고채10년'],
  ['153130.KS','KODEX 단기채권PLUS','KODEX 단기채권PLUS'],
  ['214980.KS','TIGER 단기통안채','TIGER 단기통안채'],
  ['157450.KS','TIGER 국채3년','TIGER 국채3년'],
  ['267440.KS','KODEX 국고채30년액티브','KODEX 국고채30년액티브'],
  ['385560.KS','TIGER 차이나전기차SOLACTIVE','TIGER 차이나전기차SOLACTIVE'],
  ['381170.KS','TIGER 미국S&P500','TIGER 미국S&P500'],
  ['360750.KS','TIGER 미국S&P500선물(H)','TIGER 미국S&P500선물(H)'],
  ['133690.KS','TIGER 미국나스닥100','TIGER 미국나스닥100'],
  ['367380.KS','KODEX 미국나스닥100TR','KODEX 미국나스닥100TR'],
  ['379800.KS','KODEX 미국S&P500TR','KODEX 미국S&P500TR'],
  ['143850.KS','TIGER 미국달러선물','TIGER 미국달러선물'],
  ['261240.KS','KODEX 미국달러선물','KODEX 미국달러선물'],
  ['411060.KS','ACE 미국S&P500','ACE 미국S&P500'],
  ['195920.KS','KODEX 미국S&P에너지','KODEX 미국S&P에너지'],
  ['182480.KS','TIGER 유로스탁스50(합성H)','TIGER 유로스탁스50(합성H)'],
  ['200250.KS','KOSEF 미국달러선물','KOSEF 미국달러선물'],
  ['130680.KS','TIGER 국고채10년','TIGER 국고채10년'],
  ['114800.KS','KODEX 인버스','KODEX 인버스'],
  ['251340.KS','KODEX 코스닥150선물인버스','KODEX 코스닥150선물인버스'],
  ['122630.KS','KODEX 레버리지','KODEX 레버리지'],
  ['233160.KS','TIGER 200선물인버스2X','TIGER 200선물인버스2X'],
  ['284430.KS','TIGER 200선물레버리지','TIGER 200선물레버리지'],
  ['105190.KS','TIGER 소비재','TIGER 소비재'],
  ['292150.KS','TIGER 미국필라델피아반도체나스닥','TIGER 미국필라델피아반도체나스닥'],
  ['453810.KS','KODEX 미국반도체MV','KODEX 미국반도체MV'],
  ['332620.KS','TIGER K-이차전지TOP10','TIGER K-이차전지TOP10'],
  ['460140.KS','ACE 미국빅테크TOP7Plus','ACE 미국빅테크TOP7Plus'],
  ['400760.KS','TIGER 글로벌AI&로보틱스INDXX','TIGER 글로벌AI&로보틱스INDXX'],
  ['441680.KS','KODEX 미국AI테크TOP10INDXX','KODEX 미국AI테크TOP10INDXX'],
  ['489490.KS','TIGER 미국AI반도체핵심기업MV','TIGER 미국AI반도체핵심기업MV'],
  ['487290.KS','KODEX 미국AI테크TOP10+15%프리미엄초단기','KODEX 미국AI테크TOP10+15%'],
  ['441640.KS','KODEX 미국배당커버드콜액티브','KODEX 미국배당커버드콜액티브'],
  ['466920.KS','TIGER 미국배당다우존스월배당','TIGER 미국배당다우존스월배당'],
  ['448540.KS','KODEX 미국배당프리미엄액티브','KODEX 미국배당프리미엄액티브'],
  ['459580.KS','ACE 미국배당다우존스커버드콜','ACE 미국배당다우존스커버드콜'],
  ['462050.KS','TIGER 미국나스닥100커버드콜(합성)','TIGER 미국나스닥100커버드콜'],
  ['400870.KS','KODEX 미국나스닥100데일리커버드콜OTM','KODEX 나스닥100데일리커버드콜'],
  ['446720.KS','TIGER S&P500데일리커버드콜OTM','TIGER S&P500데일리커버드콜'],
  ['476560.KS','TIGER 미국배당+7%프리미엄다우존스','TIGER 미국배당+7%프리미엄'],
  ['308620.KS','KODEX 200미국채혼합','KODEX 200미국채혼합'],
  ['360200.KS','TIGER 코스피고배당','TIGER 코스피고배당'],
  ['277630.KS','KODEX 코스피고배당','KODEX 코스피고배당'],
  ['448290.KS','ACE KRX금현물','ACE KRX금현물'],
  ['444060.KS','KODEX 금현물','KODEX 금현물'],
  ['319640.KS','TIGER 골드선물(H)','TIGER 골드선물(H)'],
  ['132030.KS','KODEX 골드선물(H)','KODEX 골드선물(H)'],
  ['411540.KS','ACE 채권혼합US리츠','ACE 채권혼합US리츠'],
  ['182490.KS','TIGER 미국리츠부동산','TIGER 미국리츠부동산'],
  ['352560.KS','KODEX 배당성장채권혼합','KODEX 배당성장채권혼합'],
  ['396520.KS','TIGER KRX바이오K-뉴딜','TIGER KRX바이오K-뉴딜'],
  ['305720.KS','KODEX 2차전지산업','KODEX 2차전지산업'],
  ['305540.KS','TIGER KRX2차전지K-뉴딜','TIGER KRX2차전지K-뉴딜'],
  ['459650.KS','TIGER 코스닥150바이오테크','TIGER 코스닥150바이오테크'],
  ['458770.KS','ACE 글로벌반도체TOP4 Plus SOLACTIVE','ACE 글로벌반도체TOP4'],
  ['394670.KS','KODEX K-방산','KODEX K-방산'],
  ['385480.KS','ACE KRX방산우주','ACE KRX방산우주'],
  ['396000.KS','TIGER 글로벌클라우드컴퓨팅INDXX','TIGER 글로벌클라우드컴퓨팅'],
  ['091180.KS','KODEX 자동차','KODEX 자동차'],
  ['244620.KS','KODEX 바이오','KODEX 바이오'],
  ['375770.KS','TIGER 미국메가테크','TIGER 미국메가테크'],
  ['459200.KS','TIGER 미국테크TOP10INDXX','TIGER 미국테크TOP10INDXX'],
  ['292340.KS','TIGER 현대차그룹+펀더멘털','TIGER 현대차그룹+펀더멘털'],
  ['425040.KS','TIGER 코리아밸류업','TIGER 코리아밸류업'],
  ['476420.KS','KODEX 코리아밸류업','KODEX 코리아밸류업'],
  ['275750.KS','TIGER 200 IT','TIGER 200 IT'],
  ['266360.KS','TIGER 코스닥150IT','TIGER 코스닥150IT'],
  ['316670.KS','KODEX 200IT TR','KODEX 200IT TR'],
  ['329200.KS','TIGER 200에너지화학','TIGER 200에너지화학'],
  ['329220.KS','TIGER 200 철강소재','TIGER 200 철강소재'],
  ['340570.KS','TIGER KRX BBIG K-뉴딜','TIGER KRX BBIG K-뉴딜'],
  ['270800.KS','KODEX 삼성그룹','KODEX 삼성그룹'],
  ['108450.KS','KODEX 삼성그룹밸류','KODEX 삼성그룹밸류'],
  ['364980.KS','TIGER 삼성그룹펀더멘털','TIGER 삼성그룹펀더멘털'],
  ['102960.KS','KODEX 국채선물10년','KODEX 국채선물10년'],
  ['302190.KS','TIGER 차이나CSI300','TIGER 차이나CSI300'],
  ['168580.KS','KODEX 중국A300','KODEX 중국A300'],
  ['200020.KS','KODEX 일본TOPIX100','KODEX 일본TOPIX100'],
  ['204480.KS','TIGER 일본니케이225','TIGER 일본니케이225'],
  ['251350.KS','TIGER 국고채30년스트립액티브','TIGER 국고채30년스트립액티브'],
  ['145600.KS','TIGER 유통','TIGER 유통'],
  ['157490.KS','TIGER 200경기소비재','TIGER 200경기소비재'],
  ['174350.KS','TIGER 200건설','TIGER 200건설'],
  ['168300.KS','TIGER 200중공업','TIGER 200중공업'],
  ['319980.KS','KODEX 모빌리티','KODEX 모빌리티'],
  ['381180.KS','TIGER 미국S&P500TR(H)','TIGER 미국S&P500TR(H)'],
  ['390390.KS','TIGER 글로벌리튬&2차전지SOLACTIVE(합성)','TIGER 글로벌리튬&2차전지'],
  ['395160.KS','TIGER 글로벌수소&미래에너지INDXX(합성)','TIGER 글로벌수소&미래에너지'],
  ['267490.KS','KODEX TDF2050액티브','KODEX TDF2050액티브'],
  ['480480.KS','TIGER 미국부동산리츠','TIGER 미국부동산리츠'],
  ['464960.KS','KODEX 미국빅테크10','KODEX 미국빅테크10'],
  ['423160.KS','TIGER Fn반도체TOP10','TIGER Fn반도체TOP10'],
  ['438090.KS','TIGER 미국S&P500+5%프리미엄초단기','TIGER 미국S&P500+5%프리미엄초단기'],
  ['480590.KS','ACE 미국30년국채액티브(H)','ACE 미국30년국채액티브(H)'],
];

// ─────────────────────────────────────────────────────────────
// 미국 ETF 순자금 상위 300
// ─────────────────────────────────────────────────────────────
const US_ETFS_RAW: R[] = [
  ['SPY','SPDR S&P 500 ETF Trust','S&P500 ETF'],
  ['IVV','iShares Core S&P 500 ETF','S&P500 ETF(IVV)'],
  ['VOO','Vanguard S&P 500 ETF','뱅가드 S&P500'],
  ['VTI','Vanguard Total Stock Market ETF','뱅가드 전체 주식시장'],
  ['QQQ','Invesco QQQ Trust','나스닥100 ETF'],
  ['VEA','Vanguard FTSE Developed Markets ETF','선진국 시장 ETF'],
  ['BND','Vanguard Total Bond Market ETF','채권 ETF'],
  ['IEFA','iShares Core MSCI EAFE ETF','EAFE ETF'],
  ['AGG','iShares Core U.S. Aggregate Bond ETF','미국 채권 ETF'],
  ['VWO','Vanguard FTSE Emerging Markets ETF','신흥국 ETF'],
  ['VUG','Vanguard Growth ETF','성장주 ETF'],
  ['IEMG','iShares Core MSCI Emerging Markets ETF','신흥국 ETF(IEMG)'],
  ['VTV','Vanguard Value ETF','가치주 ETF'],
  ['IJH','iShares Core S&P Mid-Cap ETF','중형주 ETF'],
  ['BNDX','Vanguard Total International Bond ETF','국제 채권 ETF'],
  ['IJR','iShares Core S&P Small-Cap ETF','소형주 ETF'],
  ['GLD','SPDR Gold Shares','금 ETF(GLD)'],
  ['BSV','Vanguard Short-Term Bond ETF','단기채 ETF'],
  ['VCSH','Vanguard Short-Term Corporate Bond ETF','단기 회사채 ETF'],
  ['VXUS','Vanguard Total International Stock ETF','국제 주식 ETF'],
  ['MBB','iShares MBS ETF','모기지채 ETF'],
  ['SHY','iShares 1-3 Year Treasury Bond ETF','단기국채 ETF'],
  ['IWF','iShares Russell 1000 Growth ETF','러셀1000 성장 ETF'],
  ['VGT','Vanguard Information Technology ETF','IT ETF'],
  ['VCIT','Vanguard Intermediate-Term Corporate Bond ETF','중기 회사채 ETF'],
  ['IWM','iShares Russell 2000 ETF','러셀2000 ETF'],
  ['SCHX','Schwab U.S. Large-Cap ETF','대형주 ETF(SCHX)'],
  ['IWD','iShares Russell 1000 Value ETF','러셀1000 가치 ETF'],
  ['SCHD','Schwab U.S. Dividend Equity ETF','배당주 ETF'],
  ['ITOT','iShares Core S&P Total U.S. Stock Market ETF','전체 주식시장 ETF'],
  ['LQD','iShares iBoxx $ Investment Grade Corp Bond ETF','투자등급 회사채 ETF'],
  ['VIG','Vanguard Dividend Appreciation ETF','배당성장 ETF'],
  ['SCHB','Schwab U.S. Broad Market ETF','광역 시장 ETF'],
  ['VONG','Vanguard Russell 1000 Growth ETF','러셀1000 성장 ETF(VONG)'],
  ['IEI','iShares 3-7 Year Treasury Bond ETF','중기국채 ETF'],
  ['SHV','iShares Short Treasury Bond ETF','초단기국채 ETF'],
  ['VB','Vanguard Small-Cap ETF','소형주 ETF(VB)'],
  ['XLK','Technology Select Sector SPDR Fund','기술주 섹터 ETF'],
  ['EMB','iShares J.P. Morgan USD Emerging Markets Bond ETF','신흥국 채권 ETF'],
  ['GVI','iShares Intermediate Government/Credit Bond ETF','중기 정부채 ETF'],
  ['IAU','iShares Gold Trust','금 ETF(IAU)'],
  ['HYG','iShares iBoxx $ High Yield Corporate Bond ETF','하이일드 채권 ETF'],
  ['SCHF','Schwab International Equity ETF','해외 주식 ETF'],
  ['JPST','JPMorgan Ultra-Short Income ETF','초단기 채권 ETF'],
  ['VEU','Vanguard FTSE All-World ex-US ETF','미국 외 전체 ETF'],
  ['SPAB','SPDR Portfolio Aggregate Bond ETF','채권 ETF(SPAB)'],
  ['QUAL','iShares MSCI USA Quality Factor ETF','퀄리티 팩터 ETF'],
  ['SPDW','SPDR Portfolio Developed World ex-US ETF','선진국(미국외) ETF'],
  ['DGRO','iShares Core Dividend Growth ETF','배당성장 ETF(DGRO)'],
  ['SPEM','SPDR Portfolio Emerging Markets ETF','신흥국 ETF(SPEM)'],
  ['TIP','iShares TIPS Bond ETF','물가연동채 ETF'],
  ['IEF','iShares 7-10 Year Treasury Bond ETF','7-10년 국채 ETF'],
  ['USMV','iShares MSCI USA Min Vol Factor ETF','저변동성 ETF'],
  ['TLT','iShares 20+ Year Treasury Bond ETF','장기국채 ETF'],
  ['MINT','PIMCO Enhanced Short Maturity Active ETF','단기채 액티브 ETF'],
  ['TQQQ','ProShares UltraPro QQQ','나스닥100 3배 레버리지 ETF'],
  ['SPYG','SPDR Portfolio S&P 500 Growth ETF','S&P500 성장 ETF'],
  ['SPYV','SPDR Portfolio S&P 500 Value ETF','S&P500 가치 ETF'],
  ['VLUE','iShares MSCI USA Value Factor ETF','가치 팩터 ETF'],
  ['FDL','First Trust Morningstar Dividend Leaders Index Fund','배당 ETF'],
  ['VYD','Vanguard High Dividend Yield ETF','고배당 ETF'],
  ['VYM','Vanguard High Dividend Yield ETF','고배당 ETF(VYM)'],
  ['HDV','iShares Core High Dividend ETF','고배당 ETF(HDV)'],
  ['SDY','SPDR S&P Dividend ETF','배당 ETF(SDY)'],
  ['DVY','iShares Select Dividend ETF','배당 ETF(DVY)'],
  ['NOBL','ProShares S&P 500 Dividend Aristocrats ETF','배당귀족 ETF'],
  ['DGRW','WisdomTree U.S. Quality Dividend Growth ETF','배당성장 ETF(DGRW)'],
  ['JEPI','JPMorgan Equity Premium Income ETF','주식 프리미엄 수익 ETF'],
  ['JEPQ','JPMorgan Nasdaq Equity Premium Income ETF','나스닥 프리미엄 수익 ETF'],
  ['XYLD','Global X S&P 500 Covered Call ETF','커버드콜 ETF'],
  ['QYLD','Global X Nasdaq 100 Covered Call ETF','나스닥100 커버드콜 ETF'],
  ['RYLD','Global X Russell 2000 Covered Call ETF','러셀2000 커버드콜 ETF'],
  ['NUSI','Nationwide Risk-Managed Income ETF','위험관리 수익 ETF'],
  ['DIVO','Capital Group Dividend Value ETF','배당가치 ETF'],
  ['SCHH','Schwab U.S. REIT ETF','리츠 ETF(SCHH)'],
  ['VNQ','Vanguard Real Estate ETF','부동산 ETF'],
  ['IYR','iShares U.S. Real Estate ETF','부동산 ETF(IYR)'],
  ['REM','iShares Mortgage Real Estate ETF','모기지 리츠 ETF'],
  ['XLRE','Real Estate Select Sector SPDR Fund','부동산 섹터 ETF'],
  ['O','Realty Income Corp.','리얼티 인컴'],
  ['XLF','Financial Select Sector SPDR Fund','금융 섹터 ETF'],
  ['XLE','Energy Select Sector SPDR Fund','에너지 섹터 ETF'],
  ['XLV','Health Care Select Sector SPDR Fund','헬스케어 섹터 ETF'],
  ['XLY','Consumer Discretionary Select Sector SPDR Fund','경기소비재 섹터 ETF'],
  ['XLI','Industrial Select Sector SPDR Fund','산업재 섹터 ETF'],
  ['XLC','Communication Services Select Sector SPDR Fund','통신 섹터 ETF'],
  ['XLP','Consumer Staples Select Sector SPDR Fund','필수소비재 섹터 ETF'],
  ['XLB','Materials Select Sector SPDR Fund','소재 섹터 ETF'],
  ['XLU','Utilities Select Sector SPDR Fund','유틸리티 섹터 ETF'],
  ['SOXX','iShares Semiconductor ETF','반도체 ETF'],
  ['SMH','VanEck Semiconductor ETF','반도체 ETF(SMH)'],
  ['SOXL','Direxion Daily Semiconductor Bull 3x Shares','반도체 3배 레버리지 ETF'],
  ['SOXS','Direxion Daily Semiconductor Bear 3x Shares','반도체 3배 인버스 ETF'],
  ['ARKK','ARK Innovation ETF','ARK 혁신 ETF'],
  ['ARKG','ARK Genomic Revolution ETF','ARK 유전공학 ETF'],
  ['ARKW','ARK Next Generation Internet ETF','ARK 인터넷 ETF'],
  ['ARKF','ARK Fintech Innovation ETF','ARK 핀테크 ETF'],
  ['ARKQ','ARK Autonomous Technology & Robotics ETF','ARK 자율주행 ETF'],
  ['BOTZ','Global X Robotics & Artificial Intelligence ETF','로봇&AI ETF'],
  ['ROBO','ROBO Global Robotics and Automation Index ETF','로보틱스 자동화 ETF'],
  ['AIQ','Global X Artificial Intelligence & Technology ETF','AI 테크 ETF'],
  ['CLOU','Global X Cloud Computing ETF','클라우드 컴퓨팅 ETF'],
  ['WCLD','WisdomTree Cloud Computing ETF','클라우드 ETF(WCLD)'],
  ['FINX','Global X FinTech ETF','핀테크 ETF'],
  ['IPAY','ETFMG Prime Mobile Payments ETF','모바일 결제 ETF'],
  ['BLOK','Amplify Transformational Data Sharing ETF','블록체인 ETF'],
  ['BITO','ProShares Bitcoin Strategy ETF','비트코인 선물 ETF'],
  ['IBIT','iShares Bitcoin Trust ETF','비트코인 현물 ETF(IBIT)'],
  ['FBTC','Fidelity Wise Origin Bitcoin Fund','비트코인 ETF(FBTC)'],
  ['BITB','Bitwise Bitcoin ETF','비트코인 ETF(BITB)'],
  ['GBTC','Grayscale Bitcoin Trust','그레이스케일 비트코인'],
  ['ETHA','iShares Ethereum Trust ETF','이더리움 ETF(ETHA)'],
  ['ETHU','2x Ether ETF','이더리움 2배 ETF'],
  ['CONY','YieldMax COIN Option Income Strategy ETF','코인베이스 커버드콜 ETF'],
  ['TSLY','YieldMax TSLA Option Income Strategy ETF','테슬라 커버드콜 ETF'],
  ['NVDY','YieldMax NVDA Option Income Strategy ETF','엔비디아 커버드콜 ETF'],
  ['AMZY','YieldMax AMZN Option Income Strategy ETF','아마존 커버드콜 ETF'],
  ['MSFO','YieldMax MSFT Option Income Strategy ETF','마이크로소프트 커버드콜 ETF'],
  ['GOOGY','YieldMax GOOGL Option Income Strategy ETF','구글 커버드콜 ETF'],
  ['JPMO','YieldMax JPM Option Income Strategy ETF','JP모건 커버드콜 ETF'],
  ['MRNY','YieldMax MRN Option Income Strategy ETF','MRN 커버드콜 ETF'],
  ['AMDY','YieldMax AMD Option Income Strategy ETF','AMD 커버드콜 ETF'],
  ['OARK','YieldMax Innovation Option Income Strategy ETF','ARK 커버드콜 ETF'],
  ['MSFU','MicroSectors FANG+ Index 3X Leveraged ETN','FANG+ 3배 ETN'],
  ['FNGU','MicroSectors FANG+ Index 3X Leveraged ETN','FANG+ 3배 레버리지'],
  ['FNGD','MicroSectors FANG Index -3X Inverse Leveraged ETN','FANG+ 3배 인버스'],
  ['SPXL','Direxion Daily S&P 500 Bull 3x Shares','S&P500 3배 레버리지'],
  ['SPXS','Direxion Daily S&P 500 Bear 3x Shares','S&P500 3배 인버스'],
  ['UPRO','ProShares UltraPro S&P500','S&P500 3배 레버리지(UPRO)'],
  ['SPXU','ProShares UltraPro Short S&P500','S&P500 3배 인버스(SPXU)'],
  ['SSO','ProShares Ultra S&P500','S&P500 2배 레버리지'],
  ['SDS','ProShares UltraShort S&P500','S&P500 2배 인버스'],
  ['UDOW','ProShares UltraPro Dow30','다우 3배 레버리지'],
  ['SDOW','ProShares UltraPro Short Dow30','다우 3배 인버스'],
  ['LABU','Direxion Daily S&P Biotech Bull 3X Shares','바이오테크 3배 레버리지'],
  ['LABD','Direxion Daily S&P Biotech Bear 3X Shares','바이오테크 3배 인버스'],
  ['TECL','Direxion Daily Technology Bull 3X Shares','기술주 3배 레버리지'],
  ['TECS','Direxion Daily Technology Bear 3X Shares','기술주 3배 인버스'],
  ['FAS','Direxion Daily Financial Bull 3X Shares','금융주 3배 레버리지'],
  ['FAZ','Direxion Daily Financial Bear 3X Shares','금융주 3배 인버스'],
  ['ERX','Direxion Daily Energy Bull 2X Shares','에너지 2배 레버리지'],
  ['ERY','Direxion Daily Energy Bear 2X Shares','에너지 2배 인버스'],
  ['NUGT','Direxion Daily Gold Miners Bull 2X Shares','금광주 2배 레버리지'],
  ['DUST','Direxion Daily Gold Miners Bear 2X Shares','금광주 2배 인버스'],
  ['SLV','iShares Silver Trust','은 ETF'],
  ['SIVR','Aberdeen Standard Physical Silver Shares ETF','은 ETF(SIVR)'],
  ['GDX','VanEck Gold Miners ETF','금광주 ETF'],
  ['GDXJ','VanEck Junior Gold Miners ETF','주니어 금광주 ETF'],
  ['PDBC','Invesco Optimum Yield Diversified Commodity ETF','원자재 ETF'],
  ['DBC','Invesco DB Commodity Index Tracking Fund','원자재 인덱스 ETF'],
  ['USO','United States Oil Fund','원유 ETF'],
  ['UCO','ProShares Ultra Bloomberg Crude Oil','원유 2배 ETF'],
  ['SCO','ProShares UltraShort Bloomberg Crude Oil','원유 2배 인버스 ETF'],
  ['UNG','United States Natural Gas Fund','천연가스 ETF'],
  ['DBO','Invesco DB Oil Fund','원유 DB ETF'],
  ['CPER','United States Copper Index Fund','구리 ETF'],
  ['WEAT','Teucrium Wheat Fund','밀 ETF'],
  ['CORN','Teucrium Corn Fund','옥수수 ETF'],
  ['SOYB','Teucrium Soybean Fund','콩 ETF'],
  ['EEM','iShares MSCI Emerging Markets ETF','신흥국 ETF(EEM)'],
  ['EFA','iShares MSCI EAFE ETF','EAFE ETF(EFA)'],
  ['EWJ','iShares MSCI Japan ETF','일본 ETF'],
  ['EWC','iShares MSCI Canada ETF','캐나다 ETF'],
  ['EWG','iShares MSCI Germany ETF','독일 ETF'],
  ['EWU','iShares MSCI United Kingdom ETF','영국 ETF'],
  ['EWA','iShares MSCI Australia ETF','호주 ETF'],
  ['EWZ','iShares MSCI Brazil ETF','브라질 ETF'],
  ['FXI','iShares China Large-Cap ETF','중국 대형주 ETF'],
  ['MCHI','iShares MSCI China ETF','중국 ETF(MCHI)'],
  ['KWEB','KraneShares CSI China Internet ETF','중국 인터넷 ETF'],
  ['CQQQ','Invesco China Technology ETF','중국 기술주 ETF'],
  ['EWT','iShares MSCI Taiwan ETF','대만 ETF'],
  ['EWY','iShares MSCI South Korea ETF','한국 ETF'],
  ['INDA','iShares MSCI India ETF','인도 ETF'],
  ['INDY','iShares India 50 ETF','인도50 ETF'],
  ['VNM','VanEck Vietnam ETF','베트남 ETF'],
  ['THD','iShares MSCI Thailand ETF','태국 ETF'],
  ['ECH','iShares MSCI Chile ETF','칠레 ETF'],
  ['EWW','iShares MSCI Mexico ETF','멕시코 ETF'],
  ['ARGT','Global X MSCI Argentina ETF','아르헨티나 ETF'],
  ['FM','iShares MSCI Frontier and Select EM ETF','프런티어 시장 ETF'],
  ['EDC','Direxion Daily MSCI Emerging Mkts Bull 3X Shares','신흥국 3배 레버리지'],
  ['EDZ','Direxion Daily MSCI Emerging Mkts Bear 3X Shares','신흥국 3배 인버스'],
  ['YINN','Direxion Daily FTSE China Bull 3X Shares','중국 3배 레버리지'],
  ['YANG','Direxion Daily FTSE China Bear 3X Shares','중국 3배 인버스'],
  ['TMF','Direxion Daily 20+ Year Treasury Bull 3x Shares','장기국채 3배 레버리지'],
  ['TMV','Direxion Daily 20+ Year Treasury Bear 3x Shares','장기국채 3배 인버스'],
  ['TBT','ProShares UltraShort 20+ Year Treasury','장기국채 2배 인버스'],
  ['TBF','ProShares Short 20+ Year Treasury','장기국채 인버스'],
  ['UBT','ProShares Ultra 20+ Year Treasury','장기국채 2배 레버리지'],
  ['VGLT','Vanguard Long-Term Treasury ETF','장기국채 ETF(VGLT)'],
  ['VGSH','Vanguard Short-Term Treasury ETF','단기국채 ETF(VGSH)'],
  ['VGIT','Vanguard Intermediate-Term Treasury ETF','중기국채 ETF(VGIT)'],
  ['SCHZ','Schwab U.S. Aggregate Bond ETF','채권 ETF(SCHZ)'],
  ['SCHO','Schwab Short-Term U.S. Treasury ETF','단기국채 ETF(SCHO)'],
  ['SCHR','Schwab Intermediate-Term U.S. Treasury ETF','중기국채 ETF(SCHR)'],
  ['SCHQ','Schwab Long-Term U.S. Treasury ETF','장기국채 ETF(SCHQ)'],
  ['NEAR','BlackRock Short Maturity Bond ETF','단기채 ETF(NEAR)'],
  ['FLOT','iShares Floating Rate Bond ETF','변동금리 채권 ETF'],
  ['FALN','iShares Fallen Angels USD Bond ETF','타락천사 채권 ETF'],
  ['JNK','SPDR Bloomberg High Yield Bond ETF','하이일드 ETF(JNK)'],
  ['SJNK','SPDR Bloomberg Short Term High Yield Bond ETF','단기 하이일드 ETF'],
  ['ANGL','VanEck Fallen Angel High Yield Bond ETF','타락천사 고수익 채권 ETF'],
  ['IGIB','iShares Intermediate-Term Corporate Bond ETF','중기 회사채 ETF(IGIB)'],
  ['IGSB','iShares Short-Term Corporate Bond ETF','단기 회사채 ETF(IGSB)'],
  ['IGLO','iShares 1-5 Year Investment Grade Corp Bond ETF','1-5년 투자등급채 ETF'],
  ['SPIB','SPDR Portfolio Intermediate Term Corporate Bond ETF','중기 회사채 ETF(SPIB)'],
  ['SPSB','SPDR Portfolio Short Term Corporate Bond ETF','단기 회사채 ETF(SPSB)'],
  ['SPTS','SPDR Portfolio Short Term Treasury ETF','단기국채 ETF(SPTS)'],
  ['VCLT','Vanguard Long-Term Corporate Bond ETF','장기 회사채 ETF'],
  ['VCOB','Vanguard Core Bond ETF','코어 채권 ETF'],
  ['GOVT','iShares U.S. Treasury Bond ETF','미국 국채 ETF'],
  ['GTIP','iShares Government/Credit Bond ETF','정부·회사채 ETF'],
  ['STIP','iShares 0-5 Year TIPS Bond ETF','단기 TIPS ETF'],
  ['TDTT','FlexShares iBoxx 3-Year Target Duration TIPS ETF','3년 TIPS ETF'],
  ['RINF','ProShares Inflation Expectations ETF','물가기대 ETF'],
  ['DBB','Invesco DB Base Metals Fund','비철금속 ETF'],
  ['PALL','abrdn Physical Palladium Shares ETF','팔라듐 ETF'],
  ['PPLT','abrdn Physical Platinum Shares ETF','플래티넘 ETF'],
  ['COPX','Global X Copper Miners ETF','구리 광산주 ETF'],
  ['REMX','VanEck Rare Earth/Strategic Metals ETF','희토류 ETF'],
  ['LIT','Global X Lithium & Battery Tech ETF','리튬&배터리 ETF'],
  ['PICK','iShares MSCI Global Metals & Mining Producers ETF','금속&광산 ETF'],
  ['XME','SPDR S&P Metals & Mining ETF','금속&광산 ETF(XME)'],
  ['MOO','VanEck Agribusiness ETF','농업 ETF'],
  ['DBA','Invesco DB Agriculture Fund','농업 DB ETF'],
  ['WOOD','iShares Global Timber & Forestry ETF','목재&임업 ETF'],
  ['XHB','SPDR S&P Homebuilders ETF','주택건설 ETF'],
  ['ITB','iShares U.S. Home Construction ETF','주택건설 ETF(ITB)'],
  ['NAIL','Direxion Daily Homebuilders & Supplies Bull 3X','주택건설 3배 레버리지'],
  ['IBIT','iShares Bitcoin Trust ETF','비트코인 현물 ETF'],
  ['XBI','SPDR S&P Biotech ETF','바이오테크 ETF'],
  ['IBB','iShares Biotechnology ETF','바이오테크 ETF(IBB)'],
  ['BBH','VanEck Biotech ETF','바이오테크 ETF(BBH)'],
  ['PBE','Invesco Dynamic Biotechnology & Genome ETF','바이오테크&유전체 ETF'],
  ['GNOM','Global X Genomics & Biotechnology ETF','유전공학 ETF'],
  ['EDOC','Global X Telemedicine & Digital Health ETF','원격의료 ETF'],
  ['HACK','ETFMG Prime Cyber Security ETF','사이버보안 ETF'],
  ['BUG','Global X Cybersecurity ETF','사이버보안 ETF(BUG)'],
  ['CIBR','First Trust NASDAQ Cybersecurity ETF','사이버보안 ETF(CIBR)'],
  ['SKYY','First Trust Cloud Computing ETF','클라우드 ETF(SKYY)'],
  ['PAVE','Global X U.S. Infrastructure Development ETF','인프라 ETF'],
  ['IFRA','iShares U.S. Infrastructure ETF','인프라 ETF(IFRA)'],
  ['GRID','First Trust NASDAQ Clean Edge Smart Grid ETF','스마트그리드 ETF'],
  ['ICLN','iShares Global Clean Energy ETF','청정에너지 ETF'],
  ['QCLN','First Trust NASDAQ Clean Edge Green Energy ETF','청정에너지 ETF(QCLN)'],
  ['TAN','Invesco Solar ETF','태양광 ETF'],
  ['FAN','First Trust Global Wind Energy ETF','풍력 ETF'],
  ['ACES','ALPS Clean Energy ETF','청정에너지 ETF(ACES)'],
  ['DRIV','Global X Autonomous & Electric Vehicles ETF','자율주행&전기차 ETF'],
  ['KARS','KraneShares Electric Vehicles and Future Mobility ETF','전기차 ETF(KARS)'],
  ['IDRV','iShares Self-Driving EV and Tech ETF','자율주행&EV ETF'],
  ['UFO','Procure Space ETF','우주 ETF'],
  ['ROKT','MomentumStrat New Space and Defense ETF','우주&방산 ETF'],
  ['ITA','iShares U.S. Aerospace & Defense ETF','항공우주&방산 ETF'],
  ['PPA','Invesco Aerospace & Defense ETF','항공우주&방산 ETF(PPA)'],
  ['XAR','SPDR S&P Aerospace & Defense ETF','항공우주&방산 ETF(XAR)'],
  ['DFEN','Direxion Daily Aerospace & Defense Bull 3X Shares','방산 3배 레버리지'],
  ['JETS','U.S. Global Jets ETF','항공사 ETF'],
  ['AWAY','ETFMG Travel Tech ETF','여행테크 ETF'],
  ['GAMR','Wedbush ETFMG Video Game Tech ETF','게임 ETF'],
  ['HERO','Global X Video Games & Esports ETF','게임&e스포츠 ETF'],
  ['NERD','Roundhill BITKRAFT Esports & Digital Entertainment ETF','e스포츠 ETF'],
  ['ESPO','VanEck Video Gaming and eSports ETF','게임&e스포츠 ETF(ESPO)'],
  ['META','Roundhill Ball Metaverse ETF','메타버스 ETF'],
  ['MTVR','Subversive Metaverse ETF','메타버스 ETF(MTVR)'],
  ['FMET','Fidelity Metaverse ETF','피델리티 메타버스 ETF'],
  ['AUGR','iShares Robotics and Artificial Intelligence Multisector ETF','로봇&AI ETF(AUGR)'],
  ['IRBO','iShares Robotics and Artificial Intelligence ETF','로봇&AI ETF(IRBO)'],
  ['MORT','VanEck Mortgage REIT Income ETF','모기지 리츠 ETF(MORT)'],
  ['SRET','Global X SuperDividend REIT ETF','배당 리츠 ETF'],
  ['KBWY','Invesco KBW Premium Yield Equity REIT ETF','고배당 리츠 ETF'],
  ['DFAC','Dimensional U.S. Core Equity 2 ETF','US 핵심주식 ETF'],
  ['DFAI','Dimensional International Core Equity Market ETF','국제 핵심주식 ETF'],
  ['DFAS','Dimensional U.S. Small Cap ETF','소형주 ETF(DFAS)'],
  ['DFAE','Dimensional Emerging Core Equity Market ETF','신흥국 핵심주식 ETF'],
  ['AVUV','Avantis U.S. Small Cap Value ETF','소형가치 ETF'],
  ['AVDV','Avantis International Small Cap Value ETF','국제 소형가치 ETF'],
  ['AVEM','Avantis Emerging Markets Equity ETF','신흥국 주식 ETF(AVEM)'],
  ['SCHA','Schwab U.S. Small-Cap ETF','소형주 ETF(SCHA)'],
  ['SCHM','Schwab U.S. Mid-Cap ETF','중형주 ETF(SCHM)'],
  ['SCHE','Schwab Emerging Markets Equity ETF','신흥국 ETF(SCHE)'],
  ['SCHC','Schwab International Small-Cap Equity ETF','국제 소형주 ETF'],
  ['SCHI','Schwab U.S. TIPS ETF','TIPS ETF(SCHI)'],
  ['EMLC','VanEck J.P. Morgan EM Local Currency Bond ETF','신흥국 현지화 채권 ETF'],
  ['PCY','Invesco Emerging Markets Sovereign Debt ETF','신흥국 국채 ETF'],
  ['EBND','SPDR Bloomberg Emerging Markets Local Bond ETF','신흥국 현지화 채권 ETF(EBND)'],
  ['BNDW','Vanguard Total World Bond ETF','전세계 채권 ETF'],
  ['BWX','SPDR Bloomberg International Treasury Bond ETF','국제 국채 ETF'],
  ['WIP','SPDR FTSE International Government Inflation Protected Bond ETF','국제 물가연동채 ETF'],
  ['IAGG','iShares Core International Aggregate Bond ETF','국제 채권 ETF(IAGG)'],
  ['IGOV','iShares International Treasury Bond ETF','국제 국채 ETF(IGOV)'],
  ['ILTB','iShares Core 10+ Year USD Bond ETF','10년+ 채권 ETF'],
  ['LMBS','First Trust Low Duration Opportunities ETF','저듀레이션 기회 ETF'],
  ['VMBS','Vanguard Mortgage-Backed Securities ETF','모기지채 ETF(VMBS)'],
  ['MBB','iShares MBS ETF','모기지채 ETF(MBB)'],
  ['CMBS','iShares CMBS ETF','상업용 모기지채 ETF'],
  ['PFLD','AAM Low Duration Preferred and Income Securities ETF','저듀레이션 우선주 ETF'],
  ['PFF','iShares Preferred and Income Securities ETF','우선주&수익 ETF'],
  ['PFFD','Global X U.S. Preferred ETF','미국 우선주 ETF'],
  // 한국 투자자 인기 ETF 추가
  ['TSLL','Direxion Daily TSLA Bull 2X Shares','테슬라 2배 레버리지 ETF'],
  ['QQQM','Invesco Nasdaq 100 ETF','나스닥100 ETF(소액형)'],
  ['SGOV','iShares 0-3 Month Treasury Bond ETF','초단기국채 ETF(SGOV)'],
  ['QLD','ProShares Ultra QQQ ETF','나스닥100 2배 레버리지 ETF'],
  ['SPLG','SPDR Portfolio S&P 500 ETF','S&P500 ETF(소액형)'],
];

// ─────────────────────────────────────────────────────────────
// 데이터 합치기
// ─────────────────────────────────────────────────────────────
const US_STOCKS: StockEntry[] = US_STOCKS_RAW.map(toEntry('us-stock'));
const KR_STOCKS: StockEntry[] = KR_STOCKS_RAW.map(toEntry('kr-stock'));
const KR_ETFS: StockEntry[]   = KR_ETFS_RAW.map(toEntry('kr-etf'));
const US_ETFS: StockEntry[]   = US_ETFS_RAW.map(toEntry('us-etf'));

const ALL_STOCKS: StockEntry[] = [
  ...US_STOCKS,
  ...KR_STOCKS,
  ...KR_ETFS,
  ...US_ETFS,
];

// ─────────────────────────────────────────────────────────────
// 검색 함수
// ─────────────────────────────────────────────────────────────
export function searchStocks(query: string, maxResults = 10): StockEntry[] {
  if (!query || query.trim().length === 0) return [];

  const q = query.trim().toLowerCase();

  const exact: StockEntry[]       = [];
  const tickerPrefix: StockEntry[] = [];
  const namePrefix: StockEntry[]   = [];
  const nameKrPrefix: StockEntry[] = [];
  const nameKrContains: StockEntry[] = [];
  const nameContains: StockEntry[] = [];

  for (const entry of ALL_STOCKS) {
    const tickerLow = entry.ticker.toLowerCase();
    const nameLow   = entry.name.toLowerCase();
    const nameKrLow = entry.nameKr ? entry.nameKr.toLowerCase() : '';

    if (tickerLow === q || nameLow === q || nameKrLow === q) {
      exact.push(entry);
    } else if (tickerLow.startsWith(q)) {
      tickerPrefix.push(entry);
    } else if (nameLow.startsWith(q)) {
      namePrefix.push(entry);
    } else if (nameKrLow.startsWith(q)) {
      nameKrPrefix.push(entry);
    } else if (nameKrLow.includes(q)) {
      nameKrContains.push(entry);
    } else if (nameLow.includes(q)) {
      nameContains.push(entry);
    }
  }

  const combined = [
    ...exact,
    ...tickerPrefix,
    ...namePrefix,
    ...nameKrPrefix,
    ...nameKrContains,
    ...nameContains,
  ];

  // 중복 제거 (ticker 기준)
  const seen = new Set<string>();
  const result: StockEntry[] = [];
  for (const entry of combined) {
    if (!seen.has(entry.ticker)) {
      seen.add(entry.ticker);
      result.push(entry);
    }
    if (result.length >= maxResults) break;
  }

  return result;
}

/**
 * 티커 → 표시 이름 변환
 * us-etf: 티커 그대로 (SPY, QQQ 등)
 * 그 외: 한국어 이름 우선, 없으면 영문명, 없으면 티커 그대로
 */
export function getDisplayName(ticker: string): string {
  const entry = ALL_STOCKS.find(e => e.ticker === ticker);
  if (!entry) return ticker;
  if (entry.category === 'us-etf') return ticker; // 미국 ETF는 티커 그대로
  return entry.nameKr ?? entry.name ?? ticker;
}

export { ALL_STOCKS };
